// import './object'
// import './function'
// import './typeInference'
// import './typeAlias'
// import './ts'
// import './oop/index'
// import './narrowing'
// import './main'
// import './generic'
import './DSA/hasTable'
